apiVersion: v1
kind: Service
metadata:
  name: mandelbrot-service
spec:
  # TODO: Set the service type that provisions an external IP.
  type: LoadBalancer

  selector:
    app: mandelbrot

  ports:
    # TODO: Set the external port (what clients connect to) and
    # the target port (what your container listens on).
    - port: 80
      targetPort: 3000
